# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 10:10
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20170724_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='gallery',
            field=models.ImageField(blank=True, default='', help_text='Ad Pictures', null=True, upload_to=ads.models.UploadToPathAndRename('pictures'), verbose_name='Ad Pictures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
