# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20170806_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='mapcategory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ads.MCateg'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
