# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 10:41
from __future__ import unicode_literals

import ads.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20170806_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='gallery',
            new_name='picture1',
        ),
        migrations.AddField(
            model_name='ad',
            name='picture2',
            field=models.ImageField(blank=True, default='', help_text='Ad Pictures', null=True, upload_to=ads.models.UploadToPathAndRename('pictures'), verbose_name='Ad Pictures'),
        ),
        migrations.AddField(
            model_name='ad',
            name='picture3',
            field=models.ImageField(blank=True, default='', help_text='Ad Pictures', null=True, upload_to=ads.models.UploadToPathAndRename('pictures'), verbose_name='Ad Pictures'),
        ),
        migrations.AddField(
            model_name='ad',
            name='picture4',
            field=models.ImageField(blank=True, default='', help_text='Ad Pictures', null=True, upload_to=ads.models.UploadToPathAndRename('pictures'), verbose_name='Ad Pictures'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='mapcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.MCateg'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
